### ISSUE TITLE
When a server has been found

### ISSUE THREAD

**Issue by w1lla** [Alexey1/JoinToPlayClient#1]
When a server has been found you can copy/paste the url or browse maniaplanet.exe but cant it be better to execute it right away?!

**Comment by Alexey1** [comment]
Good point! I think I should add this as an option which can be turned off because I imagine it can be annoying at times when the user is in the middle of something and MP window jumps out of nowhere. I plan to add this option soon.

**Comment by Alexey1** [comment]
Done!
